
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-osu
owner: ucsb-cs156-f25
repo_name: team02-f25-osu
pull_requests: [{"author":{"id":"MDQ6VXNlcjE5NzMxODE5","is_bot":false,"login":"Summit-Haque","name":"Summit Haque"},"headRefName":"15-edit-page-for-ucsbdiningcommonsmenuitem-plus-tests-and-stories","number":69,"title":"15 edit page for ucsbdiningcommonsmenuitem plus tests and stories","url":"https://github.com/ucsb-cs156-f25/team02-f25-osu/pull/69"},{"author":{"id":"MDQ6VXNlcjE5NzMxODE5","is_bot":false,"login":"Summit-Haque","name":"Summit Haque"},"headRefName":"14-index-page-for-ucsbdiningcommonsmenuitem-plus-tests-and-stories","number":68,"title":"14 index page for ucsbdiningcommonsmenuitem plus tests and stories","url":"https://github.com/ucsb-cs156-f25/team02-f25-osu/pull/68"},{"author":{"id":"MDQ6VXNlcjE5NzMxODE5","is_bot":false,"login":"Summit-Haque","name":"Summit Haque"},"headRefName":"13-create-page-for-ucsbdiningcommonsmenuitem-plus-tests-and-stories","number":67,"title":"13 create page for ucsbdiningcommonsmenuitem plus tests and stories","url":"https://github.com/ucsb-cs156-f25/team02-f25-osu/pull/67"},{"author":{"id":"MDQ6VXNlcjE5NzMxODE5","is_bot":false,"login":"Summit-Haque","name":"Summit Haque"},"headRefName":"12-copy-placeholders-for-ucsbdiningcommonsmenuitem-pages-add-to-appjsappnavbarjs","number":66,"title":"12 copy placeholders for ucsbdiningcommonsmenuitem pages add to appjsappnavbarjs","url":"https://github.com/ucsb-cs156-f25/team02-f25-osu/pull/66"},{"author":{"id":"MDQ6VXNlcjE5NzMxODE5","is_bot":false,"login":"Summit-Haque","name":"Summit Haque"},"headRefName":"11-table-component-for-ucsbdiningcommonsmenuitem-plus-tests","number":65,"title":"11 table component for ucsbdiningcommonsmenuitem plus tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-osu/pull/65"}]
