
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-osu
owner: ucsb-cs156-f25
repo_name: team02-f25-osu
pull_requests: [{"author":{"id":"MDQ6VXNlcjE5NzMxODE5","is_bot":false,"login":"Summit-Haque","name":"Summit Haque"},"headRefName":"5-adjust-title-and-links-in-readmemd","number":70,"title":"README.md adjusted","url":"https://github.com/ucsb-cs156-f25/team02-f25-osu/pull/70"}]
